# -*- coding: utf-8 -*-
"""2548531_LAB6_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iw8_PMO6KKX_oDn8kMcqy-NXg5Dvs_8d

**What is an Autoencoder?**
- An Autoencoder is a neural network that learns to reconstruct its own input.

**What is a Sparse Autoencoder?**
- A Sparse Autoencoder forces most neurons in the hidden layer to be inactive (close to 0).

**In Sparse Autoencoder Loss is**
- Total Loss = Reconstruction Loss + Sparsity Penalty
"""

# Importing Important Libraries
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# Image → Tensor also automatically 0-255 -> 0-1
transform = transforms.Compose([
    transforms.ToTensor(),
])


train_dataset = datasets.CIFAR10(
    root='./data',
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.CIFAR10(
    root='./data',
    train=False,
    transform=transform
)

batch_size = 64
# batch_size = images per iteration, shuffle for randomize dataset
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

class SparseAutoencoder(nn.Module):

    def __init__(self, input_dim=3072, hidden_dim=1024):
        super(SparseAutoencoder, self).__init__()

        self.encoder = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU()
        )

        self.decoder = nn.Sequential(
            nn.Linear(hidden_dim, input_dim),
            # here we need sigmoid because previously we normalize image in range of 0-1
            nn.Sigmoid()
        )

    def forward(self, x):

        encoded = self.encoder(x)

        decoded = self.decoder(encoded)

        return encoded, decoded

# encoded is output of the encoder layer. and that show how each neuron will be activated ex :- [0.5 ,0.1 ,0.05 ,.....]
# rho = target sparsity ( here, we want only 5% neurons to get activated )

def sparsity_loss(encoded, rho=0.05):
    # rho_hat is average activation of each neuron across the batch.
    rho_hat = torch.mean(encoded, dim=0)
    # compare with actual sparsity and target sparsity and calculate Squared error.
    loss = torch.sum((rho_hat - rho)**2)
    return loss

"""so for example we have 3 image batch output from encoded layer

- Image1 → [0.1, 0.9, 0.2]
- Image2 → [0.2, 0.8, 0.3]
- Image3 → [0.0, 0.7, 0.4]

by size we can see there are 3 neuron
so each average will be
- Neuron1 → (0.1+0.2+0)/3 = 0.1
- Neuron2 → (0.9+0.8+0.7)/3 = 0.8
- Neuron3 → (0.2+0.3+0.4)/3 = 0.3

and that is the rho_hat
"""

# model initialization, loss and optimizer
model = SparseAutoencoder().to(device)
criterion = nn.MSELoss() # <- its reconstruction loss
optimizer = optim.Adam(model.parameters(), lr=0.001)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

def train_model(lambda_sparse):

    model = SparseAutoencoder().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

    epochs = 10

    for epoch in range(epochs):

        total_loss = 0

        for images, _ in train_loader:

            images = images.view(images.size(0), -1).to(device)

            encoded, outputs = model(images)

            recon_loss = criterion(outputs, images)
            sparse_loss = sparsity_loss(encoded)

            loss = recon_loss + lambda_sparse * sparse_loss

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print("Epoch:", epoch, "Loss:", total_loss)

    return model

model = train_model(1e-5)

model.eval()

test_loss = 0

with torch.no_grad():

    for images, _ in test_loader:

        images = images.view(images.size(0), -1)
        images = images.to(device) # <--- Added this line to move images to the device
        encoded, outputs = model(images)
        loss = criterion(outputs, images)
        test_loss += loss.item()

print("Test Loss:", test_loss)

dataiter = iter(test_loader)
images, _ = next(dataiter)

images_flat = images.view(images.size(0), -1)
images_flat = images_flat.to(device) # Add this line to move images to the device
encoded, outputs = model(images_flat)
outputs = outputs.view(-1, 3, 32, 32)

for i in range(5):

    plt.subplot(2,5,i+1)
    plt.imshow(images[i].cpu().permute(1,2,0))
    plt.title("Original")

    plt.subplot(2,5,i+6)
    plt.imshow(outputs[i].detach().cpu().permute(1,2,0))
    plt.title("Reconstructed")

plt.show()

"""# Experiment with Diffrent learning rate"""

dataiter = iter(test_loader)
images, _ = next(dataiter)

images_flat = images.view(images.size(0), -1).to(device)

sparsity_values = [0, 1e-5, 1e-4, 1e-3]
results = []
for lam in sparsity_values:

    print("Training with lambda_sparse =", lam)
    model = train_model(lam)
    model.eval()
    with torch.no_grad():
        _, outputs = model(images_flat)

    results.append(outputs.view(-1,3,32,32).cpu())

num_images = 5
rows = len(sparsity_values) + 1

plt.figure(figsize=(12,8))

# Original images
for i in range(num_images):

    plt.subplot(rows, num_images, i+1)
    plt.imshow(images[i].permute(1,2,0))
    plt.title("Original")
    plt.axis("off")

# Reconstructed images
for r, recon in enumerate(results):

    for i in range(num_images):

        plt.subplot(rows, num_images, (r+1)*num_images + i + 1)
        plt.imshow(recon[i].permute(1,2,0))
        plt.title(f"λ={sparsity_values[r]}")
        plt.axis("off")

plt.show()

"""| Sparsity Strength | Reconstruction Quality      |
| ----------------- | --------------------------- |
| Low               | High reconstruction quality |
| Medium            | Moderate reconstruction     |
| High              | Poor reconstruction         |

Active neurons ↓

Information capacity ↓
"""

