# -*- coding: utf-8 -*-
"""2548531_LAB_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtF5jvbLx7cxWIzy5EnzcrjzgqGkN7oE

# CNN From Scrach
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist

# load data

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# reshape to (samples, channels, height, width)
x_train = x_train.reshape(-1,1,28,28)
x_test = x_test.reshape(-1,1,28,28)

# Defining Convolutional Layer

def conv_forward(image, filt, bias, stride=1):
    # extracting filter dimensions
    n_filters, n_c, f, _ = filt.shape
    # extracting image dimensions
    n_c, in_dim, _ = image.shape

    # calculating output dimension according to image and filter
    out_dim = int((in_dim - f)/stride) + 1

    # initializing output feature maps
    out = np.zeros((n_filters, out_dim, out_dim))


    # loop through each filter
    for curr_f in range(n_filters):
        curr_y = out_y = 0
        # this for moving filter vertically
        while curr_y + f <= in_dim:
            curr_x = out_x = 0
            # this for moving filter horizontally
            while curr_x + f <= in_dim:
                # the convolution operation
                out[curr_f, out_y, out_x] = np.sum(
                    filt[curr_f] * image[:, curr_y:curr_y+f, curr_x:curr_x+f]
                ) + bias[curr_f]
                # move filter position to right
                curr_x += stride
                out_x += 1
            # this for moving filter position to down
            curr_y += stride
            out_y += 1
    # returns extracted features
    return out


# this function will apply convolution filters to an input image to extract features
# it takes image, filt(kernel), bias (added after convolution) and stride (step size of filter movement) as input
# Extracting filter dimensions: n_filters is number of filters, n_c is channer (for RGB there are 3 and for our grayscale, there is only one), and f is the filter size.
# Extracting image dimensions: n_c is again channel, and in_dim is height and width
# applies multiple filters across the input image to extract important visual features
# Each filter slides across the image and computes element-wise multiplication followed by summation and bias addition
# This process generates feature maps that highlight patterns such as edges and curves, enabling the CNN to learn meaningful representations from the input

# ReLU Activation
def relu(x):
    return np.maximum(0, x)

# function takes image, size of pooling window and
# stride of pooling window as input
def maxpool(image, size=2, stride=2):
    # getting dimension of the feature mape (we get it from conv_forward functoin)
    # channer, height, weight
    n_c, h_prev, w_prev = image.shape

    # calculates the heights and weights after max pooling
    h = int((h_prev - size)/stride) + 1
    w = int((w_prev - size)/stride) + 1

    # initializing output with zeroes
    downsampled = np.zeros((n_c, h, w))

    # looping through each feature map
    for i in range(n_c):
        curr_y = out_y = 0
        # while loop to move window veritcally
        while curr_y + size <= h_prev:
            curr_x = out_x = 0
            # while loop to move window horizontally
            while curr_x + size <= w_prev:
                # select maximum value from the window
                downsampled[i, out_y, out_x] = np.max(
                    image[i, curr_y:curr_y+size, curr_x:curr_x+size]
                )
                # move window to right
                curr_x += stride
                out_x += 1
            # move window to left
            curr_y += stride
            out_y += 1
    return downsampled

# softmax converts raw output scores into probabilities
# we subtract by np.max(x) to prevent numerical overflow when exponent value become very large
# cross_entropy measures how wrong the prediction is
# if predicted probability is too far from true probability, it will assing bigger loss
# otherewise, it will assign a smaller loss


def softmax(x):
    e = np.exp(x - np.max(x))
    return e / e.sum()

def cross_entropy(pred, label):
    return -np.log(pred[label])

# Fully Connected Layer

def dense(x, W, b):
    return np.dot(W, x) + b

np.random.seed(0)


# 8 filters of 3x3 size
# dividing by 9 keeps values small and maintains stable learning
filt = np.random.randn(8,1,3,3) / 9
# to shift activation values
bias = np.zeros((8,1))

# 10 weights for 10 output classes
W = np.random.randn(10, 1352) * 0.01
# 10 biase
b = np.zeros((10,1))

# process 10 first images
for i in range(10):
  # input image
  img = x_train[i]
  # label
  label = y_train[i]

  # convolution layer
  conv = conv_forward(img, filt, bias)

  # relu activation function to remove negative values
  relu_out = relu(conv)

  # max pooling
  pool = maxpool(relu_out)

  # falttening the output
  fc_input = pool.flatten().reshape(-1,1)

  # sending it to dense layer
  out = dense(fc_input, W, b)

  # softmax activation function to count probabilities
  probs = softmax(out)

  print("Predicted:", np.argmax(probs))
  print("Actual:", label)

"""# YOLO"""

# Check GPU
!nvidia-smi

# Install YOLOv8
!pip install ultralytics

# Clone YOLOv5
!git clone https://github.com/ultralytics/yolov5

from ultralytics import YOLO
from ultralytics.utils.downloads import download

"""# YOLO V8"""

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

from ultralytics import YOLO

# taking weights and bias of YOLO v8
model_v8 = YOLO("yolov8s.pt")

# this is finetuning for our own dataset
model_v8.train(
    data="/content/drive/MyDrive/brain-tumor/brain-tumor.yaml",
    epochs=10,
    imgsz=640,
    batch=16,
    device=0,
    name="yolov8_brain"
)

model_v8.val()

model_v8.predict(source="/content/drive/MyDrive/brain-tumor/images/val",save=True)

from IPython.display import Image, display
import os

folder = "/content/runs/detect/predict"

for img in os.listdir(folder)[:5]:
    display(Image(os.path.join(folder, img)))

"""# YOLO V5"""

!cp -r /content/drive/MyDrive/brain-tumor /content/yolov5/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov5

!python train.py \
  --img 640 \
  --batch 16 \
  --epochs 10 \
  --data brain-tumor/brain-tumor.yaml \
  --weights yolov5s.pt \
  --name yolov5_brain_fixed \
  --exist-ok \
  --workers 2 \
  --cache

!ls runs/train/yolov5_brain_fixed/weights/

!python val.py \
  --weights runs/train/yolov5_brain_fixed/weights/best.pt \
  --data brain-tumor/brain-tumor.yaml \
  --img 640

!python detect.py \
  --weights runs/train/yolov5_brain_fixed/weights/best.pt \
  --source brain-tumor/images/val \
  --conf 0.25

from IPython.display import Image, display
import os

folder = "runs/detect/exp"

for img in os.listdir(folder)[:5]:
    display(Image(os.path.join(folder, img)))

"""# Comparision YOLO v5 VS YOLO v8

**Technical Interpretation**

YOLOv5:

- Higher Recall → detects more tumors
- Better mAP50 → better general detection
- Lighter model

YOLOv8:

- Better mAP50-95 → better bounding box precision
- More modern architecture
- Slightly heavier

# Ensemble Learning
"""

!pip install ensemble-boxes

from ultralytics import YOLO
import torch

# Load YOLOv8
model_v8 = YOLO("runs/detect/yolov8_brain/weights/best.pt")

# Load YOLOv5
model_v5 = torch.hub.load('ultralytics/yolov5',
                          'custom',
                          path='runs/train/yolov5_brain_fixed/weights/best.pt',
                          force_reload=True)

image_path = "/content/drive/MyDrive/brain-tumor/images/val/val_1 (1).jpg"

# YOLOv8 prediction
results_v8 = model_v8(image_path)[0]

# YOLOv5 prediction
results_v5 = model_v5(image_path)

import numpy as np
import cv2

image = cv2.imread(image_path)
h, w, _ = image.shape

def prepare_boxes(results, is_v8=True):
    boxes = []
    scores = []
    labels = []

    if is_v8:
        for box in results.boxes:
            x1, y1, x2, y2 = box.xyxy[0].cpu().numpy()
            conf = box.conf[0].cpu().numpy()
            cls = int(box.cls[0].cpu().numpy())

            boxes.append([x1/w, y1/h, x2/w, y2/h])
            scores.append(conf)
            labels.append(cls)
    else:
        for *xyxy, conf, cls in results.xyxy[0]:
            x1, y1, x2, y2 = [x.item() for x in xyxy]
            boxes.append([x1/w, y1/h, x2/w, y2/h])
            scores.append(conf.item())
            labels.append(int(cls.item()))

    return boxes, scores, labels

boxes_v8, scores_v8, labels_v8 = prepare_boxes(results_v8, True)
boxes_v5, scores_v5, labels_v5 = prepare_boxes(results_v5, False)

from ensemble_boxes import weighted_boxes_fusion

boxes_list = [boxes_v8, boxes_v5]
scores_list = [scores_v8, scores_v5]
labels_list = [labels_v8, labels_v5]

boxes, scores, labels = weighted_boxes_fusion(
    boxes_list,
    scores_list,
    labels_list,
    iou_thr=0.5,
    skip_box_thr=0.3
)

"""# Visualize image side by side"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def draw_boxes(image_path, boxes, scores, labels, color=(0,255,0), title="Model"):
    image = cv2.imread(image_path)
    h, w, _ = image.shape

    for box, score, label in zip(boxes, scores, labels):
        x1 = int(box[0] * w)
        y1 = int(box[1] * h)
        x2 = int(box[2] * w)
        y2 = int(box[3] * h)

        cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
        cv2.putText(image, f"{label}: {score:.2f}",
                    (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.5, color, 2)

    return image

# YOLOv8
boxes_v8, scores_v8, labels_v8 = prepare_boxes(results_v8, True)

# YOLOv5
boxes_v5, scores_v5, labels_v5 = prepare_boxes(results_v5, False)

# Ensemble (already computed using WBF)
boxes_ens, scores_ens, labels_ens = boxes, scores, labels

img_v8 = draw_boxes(image_path, boxes_v8, scores_v8, labels_v8, (0,255,0), "YOLOv8")
img_v5 = draw_boxes(image_path, boxes_v5, scores_v5, labels_v5, (255,0,0), "YOLOv5")
img_ens = draw_boxes(image_path, boxes_ens, scores_ens, labels_ens, (0,0,255), "Ensemble")

print(type(img_v5), img_v5.shape if img_v5 is not None else "None")
print(type(img_v8), img_v8.shape if img_v8 is not None else "None")
print(type(img_ens), img_ens.shape if img_ens is not None else "None")

from google.colab.patches import cv2_imshow
import numpy as np

combined = np.concatenate([img_v5, img_v8, img_ens], axis=1)

cv2_imshow(combined)

