# -*- coding: utf-8 -*-
"""2548531_DL_LAB5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bbFpCx8frkj0mAfs6YMR-30HyNqlT2q
"""

import torch
import torch.nn as nn
import numpy as np

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

with open("input.txt", "r", encoding="utf-8") as f:
    text = f.read().lower()

print("Length of text:", len(text))

"""## Creating Character Vocabulary & Vectorizing Text"""

# character vocabulary
chars = sorted(list(set(text)))
vocab_size = len(chars)

print("Vocabulary Size:", vocab_size)

# Character to Index mapping
char2idx = {ch: i for i, ch in enumerate(chars)}
idx2char = {i: ch for ch, i in char2idx.items()}

# Converting entire text to integer indices
encoded_text = np.array([char2idx[ch] for ch in text])

"""## Creating Training Sequences"""

sequence_length = 50
step = 1

inputs = []
targets = []

for i in range(0, len(encoded_text) - sequence_length, step):
    inputs.append(encoded_text[i:i+sequence_length])
    targets.append(encoded_text[i+sequence_length])

X = np.array(inputs)
y = np.array(targets)

print("Total sequences:", len(X))

"""## Converting to Tensors"""

X = torch.tensor(X, dtype=torch.long).to(device)
y = torch.tensor(y, dtype=torch.long).to(device)

"""## RNN Model"""

class RNNModel(nn.Module):
    def __init__(self, vocab_size, hidden_size, num_layers):
        super(RNNModel, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, hidden_size)
        self.rnn = nn.RNN(hidden_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        out, _ = self.rnn(x, h0)
        out = self.fc(out[:, -1, :])
        return out

rnn_losses = []
lstm_losses = []

"""## Train the Model"""

def train_model(model, X, y, epochs=100):
    optimizer = torch.optim.Adam(model.parameters(), lr=0.002)
    criterion = nn.CrossEntropyLoss()
    loss_history = []

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        outputs = model(X)
        loss = criterion(outputs, y)

        loss.backward()
        optimizer.step()

        loss_history.append(loss.item())
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

    return loss_history

model_rnn = RNNModel(vocab_size, 128, 2).to(device)
rnn_losses = train_model(model_rnn, X, y)



"""## LSTM Model"""

class LSTMModel(nn.Module):
    def __init__(self, vocab_size, hidden_size, num_layers):
        super(LSTMModel, self).__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.embedding = nn.Embedding(vocab_size, hidden_size)
        self.lstm = nn.LSTM(hidden_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        out, _ = self.lstm(x, (h0, c0))
        out = self.fc(out[:, -1, :])
        return out

"""## Train the Model


"""

model_lstm = LSTMModel(vocab_size, 128, 2).to(device)
lstm_losses = train_model(model_lstm, X, y)

"""## Text Generation Function"""

def generate_text(model, start_text, length=200):
    model.eval()

    input_seq = torch.tensor([char2idx[ch] for ch in start_text], dtype=torch.long).unsqueeze(0).to(device)

    generated = start_text

    for _ in range(length):
        output = model(input_seq)
        prob = torch.softmax(output, dim=1).detach().cpu().numpy()
        next_char = np.random.choice(vocab_size, p=prob[0])

        generated += idx2char[next_char]

        input_seq = torch.cat(
            [input_seq[:, 1:], torch.tensor([[next_char]]).to(device)],
            dim=1
        )

    return generated

"""## Generate New Text & Validate

### Using RNN
"""

start = "In football we need to understand "
generated_text = generate_text(model_rnn, start.lower(), 1000)

print("\nGenerated Text:\n")
print(generated_text)

"""### Using LSTM"""

start = "In football we need to understand "
generated_text = generate_text(model_lstm, start.lower(), 1000)

print("\nGenerated Text:\n")
print(generated_text)

"""## Loss vs Epoch"""

import matplotlib.pyplot as plt
import numpy as np

epochs = np.arange(1, len(rnn_losses)+1)

plt.figure()
plt.plot(epochs, rnn_losses)
plt.plot(epochs, lstm_losses)
plt.title("Training Loss vs Epoch (RNN vs LSTM)")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.show()

"""## Perplexity vs Epoch"""

rnn_perplexity = np.exp(rnn_losses)
lstm_perplexity = np.exp(lstm_losses)

plt.figure()
plt.plot(epochs, rnn_perplexity)
plt.plot(epochs, lstm_perplexity)
plt.title("Perplexity vs Epoch (RNN vs LSTM)")
plt.xlabel("Epoch")
plt.ylabel("Perplexity")
plt.show()

"""## Embedding Visualization using PCA"""

from sklearn.decomposition import PCA

# Get embedding weights from LSTM model
embeddings = model_lstm.embedding.weight.detach().cpu().numpy()

pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

plt.figure()
plt.scatter(embeddings_2d[:,0], embeddings_2d[:,1])
plt.title("Embedding Visualization using PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

from sklearn.decomposition import PCA

# Get embedding weights from RNN model
embeddings =model_rnn.embedding.weight.detach().cpu().numpy()

pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

plt.figure()
plt.scatter(embeddings_2d[:,0], embeddings_2d[:,1])
plt.title("Embedding Visualization using PCA")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

