# -*- coding: utf-8 -*-
"""2548531_DL_LAB7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1viVHn73qp6NEOYQsY4srI3VdE5FDqAKm
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

"""## Load MNIST Dataset"""

batch_size = 128

transform = transforms.ToTensor()

train_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

"""## VAE Architecture

### Encoder → produces μ and log(σ²)
### Decoder → reconstructs image from latent vector
"""

class VAE(nn.Module):

    def __init__(self):
        super(VAE, self).__init__()

        # Encoder
        self.fc1 = nn.Linear(784, 400)
        self.fc_mu = nn.Linear(400, 20)
        self.fc_logvar = nn.Linear(400, 20)

        # Decoder
        self.fc3 = nn.Linear(20, 400)
        self.fc4 = nn.Linear(400, 784)

        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    # Encoder
    def encode(self, x):
        h = self.relu(self.fc1(x))
        mu = self.fc_mu(h)
        logvar = self.fc_logvar(h)
        return mu, logvar

    # Reparameterization
    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        z = mu + eps * std
        return z

    # Decoder
    def decode(self, z):
        h = self.relu(self.fc3(z))
        return self.sigmoid(self.fc4(h))

    # Forward Pass
    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        reconstruction = self.decode(z)
        return reconstruction, mu, logvar

"""## Loss Function

### The total VAE loss consists of:

* ### Reconstruction Loss : Measures difference between input and output.



* ### KL Divergence Loss : Forces latent space to follow a normal distribution.

    * The KL divergence formula used in VAE is: D_{KL}(q(z|x) || p(z)) = -\frac{1}{2} \sum (1 + \log(\sigma^2) - \mu^2 - \sigma^2)
"""

def loss_function(recon_x, x, mu, logvar):

    # Reconstruction Loss
    recon_loss = nn.functional.binary_cross_entropy(
        recon_x, x, reduction='sum'
    )

    # KL Divergence Loss
    kl_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

    return recon_loss + kl_loss, recon_loss, kl_loss

"""## Initialize Model"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = VAE().to(device)
optimizer = optim.Adam(model.parameters(), lr=1e-3)

"""## Training Loop"""

epochs = 10

for epoch in range(epochs):

    total_loss = 0
    total_recon = 0
    total_kl = 0

    for batch_idx, (data, _) in enumerate(train_loader):

        data = data.view(-1, 784).to(device)

        optimizer.zero_grad()

        # Forward Pass
        reconstruction, mu, logvar = model(data)

        # Compute Loss
        loss, recon_loss, kl_loss = loss_function(
            reconstruction, data, mu, logvar
        )

        # Backpropagation
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_recon += recon_loss.item()
        total_kl += kl_loss.item()

    print(f"Epoch {epoch+1}")
    print("Total Loss:", total_loss/len(train_loader.dataset))
    print("Reconstruction Loss:", total_recon/len(train_loader.dataset))
    print("KL Divergence Loss:", total_kl/len(train_loader.dataset))
    print("-"*40)

"""## Latent Space Visualization"""

import matplotlib.pyplot as plt

def visualize_latent_space(model, loader):

    model.eval()

    z_points = []
    labels = []

    with torch.no_grad():
        for data, target in loader:

            data = data.view(-1,784).to(device)

            mu, logvar = model.encode(data)
            z = model.reparameterize(mu, logvar)

            z_points.append(z.cpu())
            labels.append(target)

    z_points = torch.cat(z_points)
    labels = torch.cat(labels)

    plt.figure(figsize=(8,6))
    plt.scatter(z_points[:,0], z_points[:,1], c=labels, cmap="tab10", s=5)
    plt.colorbar()
    plt.title("Latent Space Visualization")
    plt.xlabel("Z1")
    plt.ylabel("Z2")
    plt.show()

visualize_latent_space(model, train_loader)

"""## Generated Digit Samples"""

def generate_digits(model, num_samples=16):

    model.eval()

    with torch.no_grad():

        z = torch.randn(num_samples, 20).to(device)
        samples = model.decode(z).cpu()

        samples = samples.view(num_samples, 28, 28)

        plt.figure(figsize=(6,6))

        for i in range(num_samples):
            plt.subplot(4,4,i+1)
            plt.imshow(samples[i], cmap='gray')
            plt.axis("off")

        plt.suptitle("Generated Digits from Latent Space")
        plt.show()

generate_digits(model)

"""## Reconstruction Comparison"""

def show_reconstructions(model, loader):

    model.eval()

    data, _ = next(iter(loader))
    data = data[:8].to(device)

    with torch.no_grad():
        recon, _, _ = model(data.view(-1,784))

    recon = recon.view(-1,28,28).cpu()
    data = data.cpu()

    plt.figure(figsize=(10,4))

    for i in range(8):

        # Original
        plt.subplot(2,8,i+1)
        plt.imshow(data[i].squeeze(), cmap='gray')
        plt.axis("off")

        # Reconstructed
        plt.subplot(2,8,i+9)
        plt.imshow(recon[i], cmap='gray')
        plt.axis("off")

    plt.suptitle("Top: Original | Bottom: Reconstructed")
    plt.show()

show_reconstructions(model, train_loader)

